// Code generated by protoc-gen-go. DO NOT EDIT.
// source: requester/downloader/downloader.proto

package downloader

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// RangeGenMode 线程分配方式
type RangeGenMode int32

const (
	// RangeGenMode_Default 根据parallel平均生成
	RangeGenMode_Default RangeGenMode = 0
	// RangeGenMode_BlockSize 根据blockSize生成
	RangeGenMode_BlockSize RangeGenMode = 1
)

var RangeGenMode_name = map[int32]string{
	0: "Default",
	1: "BlockSize",
}

var RangeGenMode_value = map[string]int32{
	"Default":   0,
	"BlockSize": 1,
}

func (x RangeGenMode) String() string {
	return proto.EnumName(RangeGenMode_name, int32(x))
}

func (RangeGenMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_96fef423c9eadea4, []int{0}
}

//Range 请求范围
type Range struct {
	Begin                int64    `protobuf:"varint,1,opt,name=begin,proto3" json:"begin,omitempty"`
	End                  int64    `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Range) Reset()         { *m = Range{} }
func (m *Range) String() string { return proto.CompactTextString(m) }
func (*Range) ProtoMessage()    {}
func (*Range) Descriptor() ([]byte, []int) {
	return fileDescriptor_96fef423c9eadea4, []int{0}
}

func (m *Range) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Range.Unmarshal(m, b)
}
func (m *Range) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Range.Marshal(b, m, deterministic)
}
func (m *Range) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Range.Merge(m, src)
}
func (m *Range) XXX_Size() int {
	return xxx_messageInfo_Range.Size(m)
}
func (m *Range) XXX_DiscardUnknown() {
	xxx_messageInfo_Range.DiscardUnknown(m)
}

var xxx_messageInfo_Range proto.InternalMessageInfo

func (m *Range) GetBegin() int64 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *Range) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

// InstanceInfoExport 断点续传
type InstanceInfoExport struct {
	RangeGenMode         RangeGenMode `protobuf:"varint,1,opt,name=range_gen_mode,json=rangeGenMode,proto3,enum=downloader.RangeGenMode" json:"range_gen_mode,omitempty"`
	TotalSize            int64        `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	GenBegin             int64        `protobuf:"varint,3,opt,name=gen_begin,json=genBegin,proto3" json:"gen_begin,omitempty"`
	BlockSize            int64        `protobuf:"varint,4,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	Ranges               []*Range     `protobuf:"bytes,5,rep,name=ranges,proto3" json:"ranges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *InstanceInfoExport) Reset()         { *m = InstanceInfoExport{} }
func (m *InstanceInfoExport) String() string { return proto.CompactTextString(m) }
func (*InstanceInfoExport) ProtoMessage()    {}
func (*InstanceInfoExport) Descriptor() ([]byte, []int) {
	return fileDescriptor_96fef423c9eadea4, []int{1}
}

func (m *InstanceInfoExport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceInfoExport.Unmarshal(m, b)
}
func (m *InstanceInfoExport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceInfoExport.Marshal(b, m, deterministic)
}
func (m *InstanceInfoExport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceInfoExport.Merge(m, src)
}
func (m *InstanceInfoExport) XXX_Size() int {
	return xxx_messageInfo_InstanceInfoExport.Size(m)
}
func (m *InstanceInfoExport) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceInfoExport.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceInfoExport proto.InternalMessageInfo

func (m *InstanceInfoExport) GetRangeGenMode() RangeGenMode {
	if m != nil {
		return m.RangeGenMode
	}
	return RangeGenMode_Default
}

func (m *InstanceInfoExport) GetTotalSize() int64 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

func (m *InstanceInfoExport) GetGenBegin() int64 {
	if m != nil {
		return m.GenBegin
	}
	return 0
}

func (m *InstanceInfoExport) GetBlockSize() int64 {
	if m != nil {
		return m.BlockSize
	}
	return 0
}

func (m *InstanceInfoExport) GetRanges() []*Range {
	if m != nil {
		return m.Ranges
	}
	return nil
}

func init() {
	proto.RegisterEnum("downloader.RangeGenMode", RangeGenMode_name, RangeGenMode_value)
	proto.RegisterType((*Range)(nil), "downloader.Range")
	proto.RegisterType((*InstanceInfoExport)(nil), "downloader.InstanceInfoExport")
}

func init() {
	proto.RegisterFile("requester/downloader/downloader.proto", fileDescriptor_96fef423c9eadea4)
}

var fileDescriptor_96fef423c9eadea4 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x8d, 0x31, 0xd5, 0x4c, 0x6b, 0x89, 0x8b, 0x87, 0x80, 0x14, 0x4a, 0x41, 0xa8, 0x3d,
	0xb4, 0x50, 0xef, 0x1e, 0x8a, 0x22, 0x3d, 0x78, 0x89, 0x3f, 0x20, 0x6c, 0xba, 0xd3, 0x10, 0x8c,
	0x33, 0x75, 0xb3, 0x45, 0xe9, 0x4f, 0xf5, 0xd7, 0x48, 0x26, 0x11, 0x23, 0xbd, 0xcd, 0xbc, 0xdd,
	0xf7, 0xde, 0xc7, 0xc0, 0xad, 0xc5, 0x8f, 0x3d, 0x56, 0x0e, 0xed, 0xc2, 0xf0, 0x27, 0x95, 0xac,
	0xcd, 0xbf, 0x71, 0xbe, 0xb3, 0xec, 0x58, 0xc1, 0x9f, 0x32, 0x59, 0x40, 0x90, 0x68, 0xca, 0x51,
	0x5d, 0x43, 0x90, 0x61, 0x5e, 0x50, 0xec, 0x8d, 0xbd, 0xa9, 0x9f, 0x34, 0x8b, 0x8a, 0xc0, 0x47,
	0x32, 0xf1, 0xa9, 0x68, 0xf5, 0x38, 0xf9, 0xf6, 0x40, 0xad, 0xa9, 0x72, 0x9a, 0x36, 0xb8, 0xa6,
	0x2d, 0x3f, 0x7d, 0xed, 0xd8, 0x3a, 0xf5, 0x00, 0x43, 0x5b, 0xe7, 0xa4, 0x39, 0x52, 0xfa, 0xce,
	0x06, 0x25, 0x67, 0xb8, 0x8c, 0xe7, 0x9d, 0x7a, 0x69, 0x7a, 0x46, 0x7a, 0x61, 0x83, 0xc9, 0xc0,
	0x76, 0x36, 0x35, 0x02, 0x70, 0xec, 0x74, 0x99, 0x56, 0xc5, 0x01, 0xdb, 0xbe, 0x50, 0x94, 0xd7,
	0xe2, 0x80, 0xea, 0x06, 0xc2, 0x3a, 0xb8, 0x21, 0xf4, 0xe5, 0xf5, 0x22, 0x47, 0x5a, 0x09, 0xe4,
	0x08, 0x20, 0x2b, 0x79, 0xf3, 0xd6, 0x78, 0xcf, 0x1a, 0xaf, 0x28, 0xe2, 0xbd, 0x83, 0x9e, 0x54,
	0x55, 0x71, 0x30, 0xf6, 0xa7, 0xfd, 0xe5, 0xd5, 0x11, 0x52, 0xd2, 0x7e, 0x98, 0xcd, 0x60, 0xd0,
	0x65, 0x54, 0x7d, 0x38, 0x7f, 0xc4, 0xad, 0xde, 0x97, 0x2e, 0x3a, 0x51, 0x97, 0x10, 0xae, 0x7e,
	0x43, 0x23, 0x2f, 0xeb, 0xc9, 0x31, 0xef, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x38, 0x9a, 0xfb,
	0xc6, 0x75, 0x01, 0x00, 0x00,
}
