name: Build and Test
on:
  push:
    branches:
      - master
    tags:
        - v**

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: SetupGo
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: CheckoutCode
        uses: actions/checkout@v2

      - name: buildAndRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: chmod +x .github/*.sh && .github/github_build.sh
